version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo "Entered CodePipeline build"
      - gradle createElasticbeanstalkDist
  post_build:
    commands:
      - echo "Entered the post-build phase"
      - mkdir eb-dist
      - cd build/distributions/
      - unzip raven-brain-eb.zip
      - cd raven-brain-eb*
      - mv Procfile ../../../eb-dist/
      - cp -R .platform ../../../eb-dist/
      - cp -R lib ../../../eb-dist/
      - cd ../../../eb-dist
artifacts:
  files:
    - '**/*'
  base-directory: eb-dist
  name: raven-brain-eb-dist.zip