-- StrategyArea
ALTER TABLE RB_STRATEGYAREA ADD COLUMN code VARCHAR(255);
UPDATE RB_STRATEGYAREA SET code = LOWER(REPLACE(REPLACE(name, ' ', '-'), '/', '-'));
ALTER TABLE RB_STRATEGYAREA MODIFY COLUMN code VARCHAR(255) NOT NULL;
ALTER TABLE RB_STRATEGYAREA ADD CONSTRAINT strategyarea_code_format CHECK (code REGEXP '^[0-9a-zA-Z-]+$');
ALTER TABLE RB_STRATEGYAREA ADD CONSTRAINT uq_strategyarea_code_year UNIQUE (code, frcyear);

-- SequenceType
ALTER TABLE RB_SEQUENCETYPE ADD COLUMN code VARCHAR(255);
UPDATE RB_SEQUENCETYPE SET code = LOWER(REPLACE(REPLACE(name, ' ', '-'), '/', '-'));
ALTER TABLE RB_SEQUENCETYPE MODIFY COLUMN code VARCHAR(255) NOT NULL;
ALTER TABLE RB_SEQUENCETYPE ADD CONSTRAINT sequencetype_code_format CHECK (code REGEXP '^[0-9a-zA-Z-]+$');
ALTER TABLE RB_SEQUENCETYPE ADD CONSTRAINT uq_sequencetype_code_year UNIQUE (code, frcyear);
