CREATE TABLE IF NOT EXISTS RB_SEQUENCETYPE (
    name VARCHAR(255) PRIMARY KEY,
    description VARCHAR(1024)
) CHARSET = utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS RB_SEQUENCEEVENT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sequencetype_name VARCHAR(255) NOT NULL,
    eventtype_id VARCHAR(255) NOT NULL,
    startOfSequence BOOLEAN NOT NULL DEFAULT FALSE,
    endOfSequence BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_sequencetype FOREIGN KEY (sequencetype_name) REFERENCES RB_SEQUENCETYPE(name) ON DELETE CASCADE,
    CONSTRAINT fk_eventtype FOREIGN KEY (eventtype_id) REFERENCES RB_EVENTTYPE(eventtype)
) CHARSET = utf8mb4 COLLATE utf8mb4_unicode_ci;
