CREATE TABLE RB_WATCHED_TOURNAMENT (
    tournament_id VARCHAR(127) NOT NULL PRIMARY KEY,
    created       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    FOREIGN KEY (tournament_id) REFERENCES RB_TOURNAMENT (id)
)
    CHARSET = utf8mb4
    COLLATE utf8mb4_unicode_ci;
