ALTER TABLE RB_SEQUENCETYPE ADD COLUMN strategyarea_id BIGINT NOT NULL DEFAULT -1;
ALTER TABLE RB_SEQUENCETYPE ADD CONSTRAINT fk_sequencetype_strategyarea FOREIGN KEY (strategyarea_id) REFERENCES RB_STRATEGYAREA(id);
